use crate::emulator_error::EmulatorError;

use super::{arithmetic_target::ArithmeticTarget, arithmetic_target_pair::ArithmeticTargetPair};

pub enum JumpTest {
    NotZero,
    Zero,
    NotCarry,
    Carry,
    Always,
}

pub enum IncDecTarget {
    Byte(ArithmeticTarget),
    Word(ArithmeticTargetPair),
}

pub enum Instruction {
    NOP,
    JP(JumpTest),
    JPHL,
    JR(JumpTest),
    ADD(ArithmeticTarget),
    ADDHL(ArithmeticTargetPair),
    ADDSP,
    ADC(ArithmeticTarget),
    SUB(ArithmeticTarget),
    SBC(ArithmeticTarget),
    AND(ArithmeticTarget),
    OR(ArithmeticTarget),
    XOR(ArithmeticTarget),
    CP(ArithmeticTarget),
    INC(IncDecTarget),
    DEC(IncDecTarget),
    CCF,
    SCF,
    RRA,
    RLA,
    RRCA,
    RLCA,
    CPL,
    BIT(u8, ArithmeticTarget),
    RES(u8, ArithmeticTarget),
    SET(u8, ArithmeticTarget),
    SRL(ArithmeticTarget),
    RR(ArithmeticTarget),
    RL(ArithmeticTarget),
    RRC(ArithmeticTarget),
    RLC(ArithmeticTarget),
    SRA(ArithmeticTarget),
    SLA(ArithmeticTarget),
    SWAP(ArithmeticTarget),
}

impl Instruction {
    pub fn from_byte(byte: u8, prefixed: bool) -> Result<Instruction, EmulatorError> {
        if prefixed {
            Instruction::from_byte_prefixed(byte)
        } else {
            Instruction::from_byte_not_prefixed(byte)
        }
    }

    fn from_byte_prefixed(byte: u8) -> Result<Instruction, EmulatorError> {
        match byte {
            0x00 => Ok(Instruction::RLC(ArithmeticTarget::B)),
            0x01 => Ok(Instruction::RLC(ArithmeticTarget::C)),
            0x02 => Ok(Instruction::RLC(ArithmeticTarget::D)),
            0x03 => Ok(Instruction::RLC(ArithmeticTarget::E)),
            0x04 => Ok(Instruction::RLC(ArithmeticTarget::H)),
            0x05 => Ok(Instruction::RLC(ArithmeticTarget::L)),
            0x06 => Ok(Instruction::RLC(ArithmeticTarget::HL)),
            0x07 => Ok(Instruction::RLC(ArithmeticTarget::A)),
            0x08 => Ok(Instruction::RRC(ArithmeticTarget::B)),
            0x09 => Ok(Instruction::RRC(ArithmeticTarget::C)),
            0x0A => Ok(Instruction::RRC(ArithmeticTarget::D)),
            0x0B => Ok(Instruction::RRC(ArithmeticTarget::E)),
            0x0C => Ok(Instruction::RRC(ArithmeticTarget::H)),
            0x0D => Ok(Instruction::RRC(ArithmeticTarget::L)),
            0x0E => Ok(Instruction::RRC(ArithmeticTarget::HL)),
            0x0F => Ok(Instruction::RRC(ArithmeticTarget::A)),
            0x10 => Ok(Instruction::RL(ArithmeticTarget::B)),
            0x11 => Ok(Instruction::RL(ArithmeticTarget::C)),
            0x12 => Ok(Instruction::RL(ArithmeticTarget::D)),
            0x13 => Ok(Instruction::RL(ArithmeticTarget::E)),
            0x14 => Ok(Instruction::RL(ArithmeticTarget::H)),
            0x15 => Ok(Instruction::RL(ArithmeticTarget::L)),
            0x16 => Ok(Instruction::RL(ArithmeticTarget::HL)),
            0x17 => Ok(Instruction::RL(ArithmeticTarget::A)),
            0x18 => Ok(Instruction::RR(ArithmeticTarget::B)),
            0x19 => Ok(Instruction::RR(ArithmeticTarget::C)),
            0x1A => Ok(Instruction::RR(ArithmeticTarget::D)),
            0x1B => Ok(Instruction::RR(ArithmeticTarget::E)),
            0x1C => Ok(Instruction::RR(ArithmeticTarget::H)),
            0x1D => Ok(Instruction::RR(ArithmeticTarget::L)),
            0x1E => Ok(Instruction::RR(ArithmeticTarget::HL)),
            0x1F => Ok(Instruction::RR(ArithmeticTarget::A)),
            0x20 => Ok(Instruction::SLA(ArithmeticTarget::B)),
            0x21 => Ok(Instruction::SLA(ArithmeticTarget::C)),
            0x22 => Ok(Instruction::SLA(ArithmeticTarget::D)),
            0x23 => Ok(Instruction::SLA(ArithmeticTarget::E)),
            0x24 => Ok(Instruction::SLA(ArithmeticTarget::H)),
            0x25 => Ok(Instruction::SLA(ArithmeticTarget::L)),
            0x26 => Ok(Instruction::SLA(ArithmeticTarget::HL)),
            0x27 => Ok(Instruction::SLA(ArithmeticTarget::A)),
            0x28 => Ok(Instruction::SRA(ArithmeticTarget::B)),
            0x29 => Ok(Instruction::SRA(ArithmeticTarget::C)),
            0x2A => Ok(Instruction::SRA(ArithmeticTarget::D)),
            0x2B => Ok(Instruction::SRA(ArithmeticTarget::E)),
            0x2C => Ok(Instruction::SRA(ArithmeticTarget::H)),
            0x2D => Ok(Instruction::SRA(ArithmeticTarget::L)),
            0x2E => Ok(Instruction::SRA(ArithmeticTarget::HL)),
            0x2F => Ok(Instruction::SRA(ArithmeticTarget::A)),
            0x30 => Ok(Instruction::SWAP(ArithmeticTarget::B)),
            0x31 => Ok(Instruction::SWAP(ArithmeticTarget::C)),
            0x32 => Ok(Instruction::SWAP(ArithmeticTarget::D)),
            0x33 => Ok(Instruction::SWAP(ArithmeticTarget::E)),
            0x34 => Ok(Instruction::SWAP(ArithmeticTarget::H)),
            0x35 => Ok(Instruction::SWAP(ArithmeticTarget::L)),
            0x36 => Ok(Instruction::SWAP(ArithmeticTarget::HL)),
            0x37 => Ok(Instruction::SWAP(ArithmeticTarget::A)),
            0x38 => Ok(Instruction::SRL(ArithmeticTarget::B)),
            0x39 => Ok(Instruction::SRL(ArithmeticTarget::C)),
            0x3A => Ok(Instruction::SRL(ArithmeticTarget::D)),
            0x3B => Ok(Instruction::SRL(ArithmeticTarget::E)),
            0x3C => Ok(Instruction::SRL(ArithmeticTarget::H)),
            0x3D => Ok(Instruction::SRL(ArithmeticTarget::L)),
            0x3E => Ok(Instruction::SRL(ArithmeticTarget::HL)),
            0x3F => Ok(Instruction::SRL(ArithmeticTarget::A)),
            0x40 => Ok(Instruction::BIT(0, ArithmeticTarget::B)),
            0x41 => Ok(Instruction::BIT(0, ArithmeticTarget::C)),
            0x42 => Ok(Instruction::BIT(0, ArithmeticTarget::D)),
            0x43 => Ok(Instruction::BIT(0, ArithmeticTarget::E)),
            0x44 => Ok(Instruction::BIT(0, ArithmeticTarget::H)),
            0x45 => Ok(Instruction::BIT(0, ArithmeticTarget::L)),
            0x46 => Ok(Instruction::BIT(0, ArithmeticTarget::HL)),
            0x47 => Ok(Instruction::BIT(0, ArithmeticTarget::A)),
            0x48 => Ok(Instruction::BIT(1, ArithmeticTarget::B)),
            0x49 => Ok(Instruction::BIT(1, ArithmeticTarget::C)),
            0x4A => Ok(Instruction::BIT(1, ArithmeticTarget::D)),
            0x4B => Ok(Instruction::BIT(1, ArithmeticTarget::E)),
            0x4C => Ok(Instruction::BIT(1, ArithmeticTarget::H)),
            0x4D => Ok(Instruction::BIT(1, ArithmeticTarget::L)),
            0x4E => Ok(Instruction::BIT(1, ArithmeticTarget::HL)),
            0x4F => Ok(Instruction::BIT(1, ArithmeticTarget::A)),
            0x50 => Ok(Instruction::BIT(2, ArithmeticTarget::B)),
            0x51 => Ok(Instruction::BIT(2, ArithmeticTarget::C)),
            0x52 => Ok(Instruction::BIT(2, ArithmeticTarget::D)),
            0x53 => Ok(Instruction::BIT(2, ArithmeticTarget::E)),
            0x54 => Ok(Instruction::BIT(2, ArithmeticTarget::H)),
            0x55 => Ok(Instruction::BIT(2, ArithmeticTarget::L)),
            0x56 => Ok(Instruction::BIT(2, ArithmeticTarget::HL)),
            0x57 => Ok(Instruction::BIT(2, ArithmeticTarget::A)),
            0x58 => Ok(Instruction::BIT(3, ArithmeticTarget::B)),
            0x59 => Ok(Instruction::BIT(3, ArithmeticTarget::C)),
            0x5A => Ok(Instruction::BIT(3, ArithmeticTarget::D)),
            0x5B => Ok(Instruction::BIT(3, ArithmeticTarget::E)),
            0x5C => Ok(Instruction::BIT(3, ArithmeticTarget::H)),
            0x5D => Ok(Instruction::BIT(3, ArithmeticTarget::L)),
            0x5E => Ok(Instruction::BIT(3, ArithmeticTarget::HL)),
            0x5F => Ok(Instruction::BIT(3, ArithmeticTarget::A)),
            0x60 => Ok(Instruction::BIT(4, ArithmeticTarget::B)),
            0x61 => Ok(Instruction::BIT(4, ArithmeticTarget::C)),
            0x62 => Ok(Instruction::BIT(4, ArithmeticTarget::D)),
            0x63 => Ok(Instruction::BIT(4, ArithmeticTarget::E)),
            0x64 => Ok(Instruction::BIT(4, ArithmeticTarget::H)),
            0x65 => Ok(Instruction::BIT(4, ArithmeticTarget::L)),
            0x66 => Ok(Instruction::BIT(4, ArithmeticTarget::HL)),
            0x67 => Ok(Instruction::BIT(4, ArithmeticTarget::A)),
            0x68 => Ok(Instruction::BIT(5, ArithmeticTarget::B)),
            0x69 => Ok(Instruction::BIT(5, ArithmeticTarget::C)),
            0x6A => Ok(Instruction::BIT(5, ArithmeticTarget::D)),
            0x6B => Ok(Instruction::BIT(5, ArithmeticTarget::E)),
            0x6C => Ok(Instruction::BIT(5, ArithmeticTarget::H)),
            0x6D => Ok(Instruction::BIT(5, ArithmeticTarget::L)),
            0x6E => Ok(Instruction::BIT(5, ArithmeticTarget::HL)),
            0x6F => Ok(Instruction::BIT(5, ArithmeticTarget::A)),
            0x70 => Ok(Instruction::BIT(6, ArithmeticTarget::B)),
            0x71 => Ok(Instruction::BIT(6, ArithmeticTarget::C)),
            0x72 => Ok(Instruction::BIT(6, ArithmeticTarget::D)),
            0x73 => Ok(Instruction::BIT(6, ArithmeticTarget::E)),
            0x74 => Ok(Instruction::BIT(6, ArithmeticTarget::H)),
            0x75 => Ok(Instruction::BIT(6, ArithmeticTarget::L)),
            0x76 => Ok(Instruction::BIT(6, ArithmeticTarget::HL)),
            0x77 => Ok(Instruction::BIT(6, ArithmeticTarget::A)),
            0x78 => Ok(Instruction::BIT(7, ArithmeticTarget::B)),
            0x79 => Ok(Instruction::BIT(7, ArithmeticTarget::C)),
            0x7A => Ok(Instruction::BIT(7, ArithmeticTarget::D)),
            0x7B => Ok(Instruction::BIT(7, ArithmeticTarget::E)),
            0x7C => Ok(Instruction::BIT(7, ArithmeticTarget::H)),
            0x7D => Ok(Instruction::BIT(7, ArithmeticTarget::L)),
            0x7E => Ok(Instruction::BIT(7, ArithmeticTarget::HL)),
            0x7F => Ok(Instruction::BIT(7, ArithmeticTarget::A)),
            0x80 => Ok(Instruction::RES(0, ArithmeticTarget::B)),
            0x81 => Ok(Instruction::RES(0, ArithmeticTarget::C)),
            0x82 => Ok(Instruction::RES(0, ArithmeticTarget::D)),
            0x83 => Ok(Instruction::RES(0, ArithmeticTarget::E)),
            0x84 => Ok(Instruction::RES(0, ArithmeticTarget::H)),
            0x85 => Ok(Instruction::RES(0, ArithmeticTarget::L)),
            0x86 => Ok(Instruction::RES(0, ArithmeticTarget::HL)),
            0x87 => Ok(Instruction::RES(0, ArithmeticTarget::A)),
            0x88 => Ok(Instruction::RES(1, ArithmeticTarget::B)),
            0x89 => Ok(Instruction::RES(1, ArithmeticTarget::C)),
            0x8A => Ok(Instruction::RES(1, ArithmeticTarget::D)),
            0x8B => Ok(Instruction::RES(1, ArithmeticTarget::E)),
            0x8C => Ok(Instruction::RES(1, ArithmeticTarget::H)),
            0x8D => Ok(Instruction::RES(1, ArithmeticTarget::L)),
            0x8E => Ok(Instruction::RES(1, ArithmeticTarget::HL)),
            0x8F => Ok(Instruction::RES(1, ArithmeticTarget::A)),
            0x90 => Ok(Instruction::RES(2, ArithmeticTarget::B)),
            0x91 => Ok(Instruction::RES(2, ArithmeticTarget::C)),
            0x92 => Ok(Instruction::RES(2, ArithmeticTarget::D)),
            0x93 => Ok(Instruction::RES(2, ArithmeticTarget::E)),
            0x94 => Ok(Instruction::RES(2, ArithmeticTarget::H)),
            0x95 => Ok(Instruction::RES(2, ArithmeticTarget::L)),
            0x96 => Ok(Instruction::RES(2, ArithmeticTarget::HL)),
            0x97 => Ok(Instruction::RES(2, ArithmeticTarget::A)),
            0x98 => Ok(Instruction::RES(3, ArithmeticTarget::B)),
            0x99 => Ok(Instruction::RES(3, ArithmeticTarget::C)),
            0x9A => Ok(Instruction::RES(3, ArithmeticTarget::D)),
            0x9B => Ok(Instruction::RES(3, ArithmeticTarget::E)),
            0x9C => Ok(Instruction::RES(3, ArithmeticTarget::H)),
            0x9D => Ok(Instruction::RES(3, ArithmeticTarget::L)),
            0x9E => Ok(Instruction::RES(3, ArithmeticTarget::HL)),
            0x9F => Ok(Instruction::RES(3, ArithmeticTarget::A)),
            0xA0 => Ok(Instruction::RES(4, ArithmeticTarget::B)),
            0xA1 => Ok(Instruction::RES(4, ArithmeticTarget::C)),
            0xA2 => Ok(Instruction::RES(4, ArithmeticTarget::D)),
            0xA3 => Ok(Instruction::RES(4, ArithmeticTarget::E)),
            0xA4 => Ok(Instruction::RES(4, ArithmeticTarget::H)),
            0xA5 => Ok(Instruction::RES(4, ArithmeticTarget::L)),
            0xA6 => Ok(Instruction::RES(4, ArithmeticTarget::HL)),
            0xA7 => Ok(Instruction::RES(4, ArithmeticTarget::A)),
            0xA8 => Ok(Instruction::RES(5, ArithmeticTarget::B)),
            0xA9 => Ok(Instruction::RES(5, ArithmeticTarget::C)),
            0xAA => Ok(Instruction::RES(5, ArithmeticTarget::D)),
            0xAB => Ok(Instruction::RES(5, ArithmeticTarget::E)),
            0xAC => Ok(Instruction::RES(5, ArithmeticTarget::H)),
            0xAD => Ok(Instruction::RES(5, ArithmeticTarget::L)),
            0xAE => Ok(Instruction::RES(5, ArithmeticTarget::HL)),
            0xAF => Ok(Instruction::RES(5, ArithmeticTarget::A)),
            0xB0 => Ok(Instruction::RES(6, ArithmeticTarget::B)),
            0xB1 => Ok(Instruction::RES(6, ArithmeticTarget::C)),
            0xB2 => Ok(Instruction::RES(6, ArithmeticTarget::D)),
            0xB3 => Ok(Instruction::RES(6, ArithmeticTarget::E)),
            0xB4 => Ok(Instruction::RES(6, ArithmeticTarget::H)),
            0xB5 => Ok(Instruction::RES(6, ArithmeticTarget::L)),
            0xB6 => Ok(Instruction::RES(6, ArithmeticTarget::HL)),
            0xB7 => Ok(Instruction::RES(6, ArithmeticTarget::A)),
            0xB8 => Ok(Instruction::RES(7, ArithmeticTarget::B)),
            0xB9 => Ok(Instruction::RES(7, ArithmeticTarget::C)),
            0xBA => Ok(Instruction::RES(7, ArithmeticTarget::D)),
            0xBB => Ok(Instruction::RES(7, ArithmeticTarget::E)),
            0xBC => Ok(Instruction::RES(7, ArithmeticTarget::H)),
            0xBD => Ok(Instruction::RES(7, ArithmeticTarget::L)),
            0xBE => Ok(Instruction::RES(7, ArithmeticTarget::HL)),
            0xBF => Ok(Instruction::RES(7, ArithmeticTarget::A)),
            0xC0 => Ok(Instruction::SET(0, ArithmeticTarget::B)),
            0xC1 => Ok(Instruction::SET(0, ArithmeticTarget::C)),
            0xC2 => Ok(Instruction::SET(0, ArithmeticTarget::D)),
            0xC3 => Ok(Instruction::SET(0, ArithmeticTarget::E)),
            0xC4 => Ok(Instruction::SET(0, ArithmeticTarget::H)),
            0xC5 => Ok(Instruction::SET(0, ArithmeticTarget::L)),
            0xC6 => Ok(Instruction::SET(0, ArithmeticTarget::HL)),
            0xC7 => Ok(Instruction::SET(0, ArithmeticTarget::A)),
            0xC8 => Ok(Instruction::SET(1, ArithmeticTarget::B)),
            0xC9 => Ok(Instruction::SET(1, ArithmeticTarget::C)),
            0xCA => Ok(Instruction::SET(1, ArithmeticTarget::D)),
            0xCB => Ok(Instruction::SET(1, ArithmeticTarget::E)),
            0xCC => Ok(Instruction::SET(1, ArithmeticTarget::H)),
            0xCD => Ok(Instruction::SET(1, ArithmeticTarget::L)),
            0xCE => Ok(Instruction::SET(1, ArithmeticTarget::HL)),
            0xCF => Ok(Instruction::SET(1, ArithmeticTarget::A)),
            0xD0 => Ok(Instruction::SET(2, ArithmeticTarget::B)),
            0xD1 => Ok(Instruction::SET(2, ArithmeticTarget::C)),
            0xD2 => Ok(Instruction::SET(2, ArithmeticTarget::D)),
            0xD3 => Ok(Instruction::SET(2, ArithmeticTarget::E)),
            0xD4 => Ok(Instruction::SET(2, ArithmeticTarget::H)),
            0xD5 => Ok(Instruction::SET(2, ArithmeticTarget::L)),
            0xD6 => Ok(Instruction::SET(2, ArithmeticTarget::HL)),
            0xD7 => Ok(Instruction::SET(2, ArithmeticTarget::A)),
            0xD8 => Ok(Instruction::SET(3, ArithmeticTarget::B)),
            0xD9 => Ok(Instruction::SET(3, ArithmeticTarget::C)),
            0xDA => Ok(Instruction::SET(3, ArithmeticTarget::D)),
            0xDB => Ok(Instruction::SET(3, ArithmeticTarget::E)),
            0xDC => Ok(Instruction::SET(3, ArithmeticTarget::H)),
            0xDD => Ok(Instruction::SET(3, ArithmeticTarget::L)),
            0xDE => Ok(Instruction::SET(3, ArithmeticTarget::HL)),
            0xDF => Ok(Instruction::SET(3, ArithmeticTarget::A)),
            0xE0 => Ok(Instruction::SET(4, ArithmeticTarget::B)),
            0xE1 => Ok(Instruction::SET(4, ArithmeticTarget::C)),
            0xE2 => Ok(Instruction::SET(4, ArithmeticTarget::D)),
            0xE3 => Ok(Instruction::SET(4, ArithmeticTarget::E)),
            0xE4 => Ok(Instruction::SET(4, ArithmeticTarget::H)),
            0xE5 => Ok(Instruction::SET(4, ArithmeticTarget::L)),
            0xE6 => Ok(Instruction::SET(4, ArithmeticTarget::HL)),
            0xE7 => Ok(Instruction::SET(4, ArithmeticTarget::A)),
            0xE8 => Ok(Instruction::SET(5, ArithmeticTarget::B)),
            0xE9 => Ok(Instruction::SET(5, ArithmeticTarget::C)),
            0xEA => Ok(Instruction::SET(5, ArithmeticTarget::D)),
            0xEB => Ok(Instruction::SET(5, ArithmeticTarget::E)),
            0xEC => Ok(Instruction::SET(5, ArithmeticTarget::H)),
            0xED => Ok(Instruction::SET(5, ArithmeticTarget::L)),
            0xEE => Ok(Instruction::SET(5, ArithmeticTarget::HL)),
            0xEF => Ok(Instruction::SET(5, ArithmeticTarget::A)),
            0xF0 => Ok(Instruction::SET(6, ArithmeticTarget::B)),
            0xF1 => Ok(Instruction::SET(6, ArithmeticTarget::C)),
            0xF2 => Ok(Instruction::SET(6, ArithmeticTarget::D)),
            0xF3 => Ok(Instruction::SET(6, ArithmeticTarget::E)),
            0xF4 => Ok(Instruction::SET(6, ArithmeticTarget::H)),
            0xF5 => Ok(Instruction::SET(6, ArithmeticTarget::L)),
            0xF6 => Ok(Instruction::SET(6, ArithmeticTarget::HL)),
            0xF7 => Ok(Instruction::SET(6, ArithmeticTarget::A)),
            0xF8 => Ok(Instruction::SET(7, ArithmeticTarget::B)),
            0xF9 => Ok(Instruction::SET(7, ArithmeticTarget::C)),
            0xFA => Ok(Instruction::SET(7, ArithmeticTarget::D)),
            0xFB => Ok(Instruction::SET(7, ArithmeticTarget::E)),
            0xFC => Ok(Instruction::SET(7, ArithmeticTarget::H)),
            0xFD => Ok(Instruction::SET(7, ArithmeticTarget::L)),
            0xFE => Ok(Instruction::SET(7, ArithmeticTarget::HL)),
            0xFF => Ok(Instruction::SET(7, ArithmeticTarget::A)),
            _ => Err(EmulatorError::UnknownInstruction(byte)),
        }
    }

    fn from_byte_not_prefixed(byte: u8) -> Result<Instruction, EmulatorError> {
        match byte {
            0x00 => Ok(Instruction::NOP),
            0x03 => Ok(Instruction::INC(IncDecTarget::Word(
                ArithmeticTargetPair::BC,
            ))),
            0x04 => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::B))),
            0x05 => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::B))),
            0x07 => Ok(Instruction::RLCA),
            0x09 => Ok(Instruction::ADDHL(ArithmeticTargetPair::BC)),
            0x0B => Ok(Instruction::DEC(IncDecTarget::Word(
                ArithmeticTargetPair::BC,
            ))),
            0x0C => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::C))),
            0x0D => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::C))),
            0x0F => Ok(Instruction::RRCA),
            0x13 => Ok(Instruction::INC(IncDecTarget::Word(
                ArithmeticTargetPair::DE,
            ))),
            0x14 => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::D))),
            0x15 => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::D))),
            0x17 => Ok(Instruction::RLA),
            0x18 => Ok(Instruction::JR(JumpTest::Always)),
            0x19 => Ok(Instruction::ADDHL(ArithmeticTargetPair::DE)),
            0x1B => Ok(Instruction::DEC(IncDecTarget::Word(
                ArithmeticTargetPair::DE,
            ))),
            0x1C => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::E))),
            0x1D => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::E))),
            0x1F => Ok(Instruction::RRA),
            0x20 => Ok(Instruction::JR(JumpTest::NotZero)),
            0x23 => Ok(Instruction::INC(IncDecTarget::Word(
                ArithmeticTargetPair::HL,
            ))),
            0x24 => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::H))),
            0x25 => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::H))),
            0x28 => Ok(Instruction::JR(JumpTest::Zero)),
            0x29 => Ok(Instruction::ADDHL(ArithmeticTargetPair::HL)),
            0x2B => Ok(Instruction::DEC(IncDecTarget::Word(
                ArithmeticTargetPair::HL,
            ))),
            0x2C => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::L))),
            0x2D => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::L))),
            0x2F => Ok(Instruction::CPL),
            0x30 => Ok(Instruction::JR(JumpTest::NotCarry)),
            0x33 => Ok(Instruction::INC(IncDecTarget::Word(
                ArithmeticTargetPair::SP,
            ))),
            0x34 => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::HL))),
            0x35 => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::HL))),
            0x38 => Ok(Instruction::JR(JumpTest::Carry)),
            0x39 => Ok(Instruction::ADDHL(ArithmeticTargetPair::SP)),
            0x3B => Ok(Instruction::DEC(IncDecTarget::Word(
                ArithmeticTargetPair::SP,
            ))),
            0x3C => Ok(Instruction::INC(IncDecTarget::Byte(ArithmeticTarget::A))),
            0x3D => Ok(Instruction::DEC(IncDecTarget::Byte(ArithmeticTarget::A))),
            0x3F => Ok(Instruction::CCF),
            0x80 => Ok(Instruction::ADD(ArithmeticTarget::B)),
            0x81 => Ok(Instruction::ADD(ArithmeticTarget::C)),
            0x82 => Ok(Instruction::ADD(ArithmeticTarget::D)),
            0x83 => Ok(Instruction::ADD(ArithmeticTarget::E)),
            0x84 => Ok(Instruction::ADD(ArithmeticTarget::H)),
            0x85 => Ok(Instruction::ADD(ArithmeticTarget::L)),
            0x86 => Ok(Instruction::ADD(ArithmeticTarget::HL)),
            0x87 => Ok(Instruction::ADD(ArithmeticTarget::A)),
            0x88 => Ok(Instruction::ADC(ArithmeticTarget::B)),
            0x89 => Ok(Instruction::ADC(ArithmeticTarget::C)),
            0x8A => Ok(Instruction::ADC(ArithmeticTarget::D)),
            0x8B => Ok(Instruction::ADC(ArithmeticTarget::E)),
            0x8C => Ok(Instruction::ADC(ArithmeticTarget::H)),
            0x8D => Ok(Instruction::ADC(ArithmeticTarget::L)),
            0x8E => Ok(Instruction::ADC(ArithmeticTarget::HL)),
            0x8F => Ok(Instruction::ADC(ArithmeticTarget::A)),
            0x90 => Ok(Instruction::SUB(ArithmeticTarget::B)),
            0x91 => Ok(Instruction::SUB(ArithmeticTarget::C)),
            0x92 => Ok(Instruction::SUB(ArithmeticTarget::D)),
            0x93 => Ok(Instruction::SUB(ArithmeticTarget::E)),
            0x94 => Ok(Instruction::SUB(ArithmeticTarget::H)),
            0x95 => Ok(Instruction::SUB(ArithmeticTarget::L)),
            0x96 => Ok(Instruction::SUB(ArithmeticTarget::HL)),
            0x97 => Ok(Instruction::SUB(ArithmeticTarget::A)),
            0x98 => Ok(Instruction::SBC(ArithmeticTarget::B)),
            0x99 => Ok(Instruction::SBC(ArithmeticTarget::C)),
            0x9A => Ok(Instruction::SBC(ArithmeticTarget::D)),
            0x9B => Ok(Instruction::SBC(ArithmeticTarget::E)),
            0x9C => Ok(Instruction::SBC(ArithmeticTarget::H)),
            0x9D => Ok(Instruction::SBC(ArithmeticTarget::L)),
            0x9E => Ok(Instruction::SBC(ArithmeticTarget::HL)),
            0x9F => Ok(Instruction::SBC(ArithmeticTarget::A)),
            0xA0 => Ok(Instruction::AND(ArithmeticTarget::B)),
            0xA1 => Ok(Instruction::AND(ArithmeticTarget::C)),
            0xA2 => Ok(Instruction::AND(ArithmeticTarget::D)),
            0xA3 => Ok(Instruction::AND(ArithmeticTarget::E)),
            0xA4 => Ok(Instruction::AND(ArithmeticTarget::H)),
            0xA5 => Ok(Instruction::AND(ArithmeticTarget::L)),
            0xA6 => Ok(Instruction::AND(ArithmeticTarget::HL)),
            0xA7 => Ok(Instruction::AND(ArithmeticTarget::A)),
            0xA8 => Ok(Instruction::XOR(ArithmeticTarget::B)),
            0xA9 => Ok(Instruction::XOR(ArithmeticTarget::C)),
            0xAA => Ok(Instruction::XOR(ArithmeticTarget::D)),
            0xAB => Ok(Instruction::XOR(ArithmeticTarget::E)),
            0xAC => Ok(Instruction::XOR(ArithmeticTarget::H)),
            0xAD => Ok(Instruction::XOR(ArithmeticTarget::L)),
            0xAE => Ok(Instruction::XOR(ArithmeticTarget::HL)),
            0xAF => Ok(Instruction::XOR(ArithmeticTarget::A)),
            0xB0 => Ok(Instruction::OR(ArithmeticTarget::B)),
            0xB1 => Ok(Instruction::OR(ArithmeticTarget::C)),
            0xB2 => Ok(Instruction::OR(ArithmeticTarget::D)),
            0xB3 => Ok(Instruction::OR(ArithmeticTarget::E)),
            0xB4 => Ok(Instruction::OR(ArithmeticTarget::H)),
            0xB5 => Ok(Instruction::OR(ArithmeticTarget::L)),
            0xB6 => Ok(Instruction::OR(ArithmeticTarget::HL)),
            0xB7 => Ok(Instruction::OR(ArithmeticTarget::A)),
            0xC2 => Ok(Instruction::JP(JumpTest::NotZero)),
            0xC3 => Ok(Instruction::JP(JumpTest::Always)),
            0xCA => Ok(Instruction::JP(JumpTest::Zero)),
            0xD2 => Ok(Instruction::JP(JumpTest::NotCarry)),
            0xDA => Ok(Instruction::JP(JumpTest::Carry)),
            0xE8 => Ok(Instruction::ADDSP),
            0xE9 => Ok(Instruction::JPHL),
            _ => Err(EmulatorError::UnknownInstruction(byte)),
        }
    }
}
